services:
  api:
    container_name: $COMPOSE_PROJECT_NAME-api
    image: $COMPOSE_PROJECT_NAME-api:dev
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      DOTNET_ENVIRONMENT: Development
  ui:
    container_name: $COMPOSE_PROJECT_NAME-ui
    image: $COMPOSE_PROJECT_NAME-ui:dev
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./ui/.env
