services:
  api:
    container_name: $PROJECT-api
    image: $PROJECT-api:dev
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
  ui:
    container_name: $PROJECT-ui
    image: $PROJECT-ui:dev
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
    ports:
      - "8081:8080"
